{% set name = "ml-research" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ml-research-{{ version }}.tar.gz
  sha256: c4964526307d997c23e9202a3830b483535b7e740f8fa826689f806f58d2fdd2

build:
  # noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy >=1.14
    - pandas >=1.3.5
    - imbalanced-learn >=0.8.0
    - matplotlib-base
    - requests
    - rich
    - scikit-learn >=1.0.0

test:
  imports:
    - mlresearch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/joaopfonseca/ml-research
  summary: Implementation of Machine Learning algorithms, experiments and utilities.
  license: MIT
  license_file: LICENSE
  doc_url: https://mlresearch.readthedocs.io

extra:
  recipe-maintainers:
    - joaopfonseca
